<?php

$t_arbol = "ID_PADRE, ID_HIJO, NOMBRE_RAMA, ORDEN_RAMA, NIVEL_RAMA, FARMACO, LINK_RAMA, TIPO_LINK, NOTA_RAMA, ORDEN_LISTADO, DESCRIPCION_FARMACO, USOS_FARMACO, CONTRAINDICACIONES_FARMACO, PRECAUCIONES_FARMACO, REACCIONES_ADVERSAS_FARMACO, INTERACCIONES_FARMACO, DOSIS_FARMACO, DEFINICION_FARMACO, Id_Raiz, MONODROGA, PRINCIPIO_ACTIVO, ACCION_TERAPEUTICA, EMBARAZO_FARMACO, LACTANCIA_FARMACO, CATEGORIA_FARMACO, COD_ATC, FECHA_LANZAMIENTO, COD_FTM";
$t_ciudad = "ID_PAIS, ID_REGION, ID_CIUDAD, NOMBRE_CIUDAD";
$t_empresa = "ID_EMPRESA, ID_PAIS, ID_REGION, ID_CIUDAD, RAZONSOCIAL_EMPRESA, RUC_EMPRESA, DIRECCION_EMPRESA, TELEFONO1_EMPRESA, TELEFONO2_EMPRESA, FAX1_EMPRESA, COMENTARIO_EMPRESA, CORREOELECTRONICO_EMPRESA, FECHAULTIMAREUNION_EMPRESA, REFERIDOPOR_EMPRES, CODIGOPOSTAL_EMPRE, NOTAS_EMPRESA, WEB_EMPRESA1";
$t_farmaco_producto = "ID_HIJO, ID_PRODUCTO, ID_VIACON";
$t_laboratorio = "ID_LABORATORIO, ID_EMPRESA, NOMBRE_LABORATORIO";
$t_linea = "ID_LINEA, ID_LABORATORIO, ID_TIPO_LINEA, ID_PAIS, ID_REGION, ID_CIUDAD, NOMBRE_COMERCIAL_LINEA";
$t_posologia = "ID, ID_HIJO, ID_PAIS, POSOLOGIA, ORIGINAL, FORMATO_POSOLOGIA";
$t_producto = "ID_PRODUCTO, ID_LINEA, NOMBRE_PRODUCTO, COMPOSICION_PRODUCTO, FECHA_PRECIO_PRODUCTO, PRECIO_PRODUCTO, PRESENTACION_PRODUCTO, ACTUALIZABLE_PRODUCTO, Activo_Producto, Fecha_Ingreso, PSICOFARMACO, NUMERO_PAGINA, PRECIODROG_PRODUCTO, IMPUESTO, CB, CAMPO_M, TIPORECETA_PRODUCTO, ID_PRESENTACION_CONCENTRACION, ID_PRESENTACION_PRESENTACION, ID_PRESENTACION_UNIDAD, Cod_Barras, Extra1, Extra2, Extra3, Farmadescuento, PRESENTACION_AGRUPADA, FECHA_ALTA, PRECIO_VENTA_PUBLICO, AMPP_ID_DNMA, AMPP_ID_SNOMED, AMPP_ID_INTERNO, AMP_ID_DNMA, AMP_ID_SNOMED, AMP_ID_INTERNO, DNMA_ID, SNOMED_ID";
$t_region = "ID_PAIS, ID_REGION, NOMBRE_REGION";
$via_concentracion = "ID_VIACON, descripcion_viacon";
